### PR TITLE
ENH+BF: added paragraph+asciinema for heudiconv

### PR DESCRIPTION
**Pull request by yarikoptic**
I also copied a sample .cmds file for now but wasn't sure on the best way to incorporate it.

### CODE REVIEW

**Comment by yarikoptic** [comment]
ah silly me -- those .sh scripts aren't the "scripts" really -- they are "cast scripts"... will remove and force push in a second.

**Comment by aqw** [comment]
@yarikoptic I believe the command you want to use is:

`tools/cast2script docs/casts/heudiconv_dicom_to_bids.sh`

---Alex

**Comment by yarikoptic** [comment]
I already cleaned it up ;-)

**Comment by aqw** [comment]
@yarikoptic Pushed?

**Comment by aqw** [comment]
@yarikoptic Merged. I cleaned up some of the language and generated the `heudiconv_dicom_to_bids.sh` for you.

A few things:
1) I deleted `heudiconv_dicom_to_bids.cmds` because I didn't see the value in it. All the commands are listed in the .sh file, and the full timing is available in the asciicast. If you feel I have overreached, let me know and we can discuss.
2) Please take a look at the title "Automation and Control of Data Acquisition". It is long and I feel it poorly reflects the information covered in that section. It should be improved upon.

Thanks again for the PR. :-)

---Alex

**Comment by yarikoptic** [comment]
Here is how those .cmds getting their 2nd life:  https://asciinema.org/a/134832 ;-)

Title:  yeah, didn't like it either ;) thanks @aqw  ;)  may be straight to the point --  "BIDS DataLad Datasets"  or  better more specific "Automated Creation of BIDS DataLad Datasets"?

**Comment by aqw** [comment]
@yarikoptic You still havn't explained what tangible value those .cmd files provide that the .sh script and .json don't cover.

I see the .cmd files have command duration, but I can't come up with a real scenario where that is useful.

---Alex

**Comment by aqw** [comment]
@yarikoptic Ahh, if the point of that paragraph is to highlight the use of BIDS, that wasn't clear. It does meander a bit. Please confirm if that is indeed the case, and I can take a stab at rewriting it to be more direct.

---Alex

**Comment by yarikoptic** [comment]
@aqw re .cmd files -- to centralize the description I have expanded the third item in https://github.com/datalad/datalad.org/issues/23

**Pull request closed without merging**
