### PR TITLE
ENH: absorb explicit Portal block, fix few links, provide more hrefs

### PR DESCRIPTION
**Pull request by yarikoptic**
- Made entry boxes have uniform Imperative formulation (removed also 'data' since it is not just about data, and otherwise it is assumed)
- removed "Portal" and absorbed links into "Discover"
- added trailing button to guide into Features
- few other minor fixups etc

this is how it looks:
index

I think it would be nice if `Features` page provided even more of "seamless" pointers into documentation for related concepts/actions... this way users would get high level overview while being able to quickly get to the related details (also that is a part of my intention for those "[help]" links in the commands transcript for screencasts).

### CODE REVIEW

**Comment by aqw** [comment]
@yarikoptic  I think dropping "data" is a bad idea. Let's play the game word-association:

- discover - the unknown
- consume - food
- publish - papers
- reproduce - procreate

None of these have to do with data.

Could you please explain your rational for combining portal into discover?

Why do you feel that the button for "see more features" should be more eye-catching than the features that are important enough for us to include on the main page?

The failures of the in-page navigation of the features page is known. Please open a separate issue for that. I can't believe I have to explain this to you of all people: one issue per problem/suggestion. Otherwise you make it much more difficult to have clear, on-topic conversations.

---Alex

**Comment by yarikoptic** [comment]
On August 26, 2017 7:43:47 AM EDT, Alex Waite <notifications@github.com> wrote:
>@yarikoptic  I think dropping "data" is a bad idea. Let's play the game
>word-association:
>
>- discover - the unknown
>- consume - food
>- publish - papers
>- reproduce - procreate
>
>None of these have to do with data.
>
>Could you please explain your rational for combining portal into
>discover?
>
>Why do you feel that the button for "see more features" should be more
>eye-catching than the features that are important enough for us to
>include on the main page?
>
>The failures of the in-page navigation of the features page is known.
>Please open a separate issue for that. I can't believe I have to
>explain this to you of all people: one issue per problem/suggestion.
>Otherwise you make it much more difficult to have clear, on-topic
>conversations.
>
>---Alex
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/datalad/datalad.org/pull/27#issuecomment-325118712

Let's add this particular reply of yours into being Yarik game... But now only with priors, and without my reply coming first ;-)

 How should I reply to your last comment given an additional prior that 

- YOU have sent entire 0 pull requests if I remember correctly against this repository while redoing it entirely

**Comment by yarikoptic** [comment]
Ok, can readd data

Emphasising on Portal suggests that we are providing hosting! Also discovery isn't possible without portal...

**Comment by yarikoptic** [comment]
Added see more features because those 4 blocks are just the big ones but we have more, and I felt that it is good to guide people into the next step (below that just Twitter icon etc)

**Comment by yarikoptic** [comment]
On a 3rd thought, adding nouns to those verbs is imho really not needed -- from the project name, slogan, description in each box it is clear what we are talking about (data).  Moreover now I have recalled why I didn't like explicit "data".  Because indeed all of those actions and datalad itself is applicable to any content, including code, documents, music, papers.  So why to limit?

**Comment by aqw** [comment]
@yarikoptic 

- "Portal" is a known bad word. I won't defend it. Provide a better word that we all can agree on please.
- I didn't criticize you adding the button; I asked why you made it visually impactful.
- You have a point about "data" being too specific. But I still think that sans-"data" makes those verbs mean something different than what we mean. I don't like repeating the same word over and over though. Suggestions?

---Alex

**Comment by yarikoptic** [comment]
1. `Distribution`?
2. To some degree for uniform appearance of those "do next" items, and to the other - since it was easiest to use the same styling/construct (I even noted  that it was a "class" not "id" defining the style, so felt easy to do so)
3. My suggestion remains -- do not include "data" explicitly in all the items

**Comment by yarikoptic** [comment]
I will close this one for now since I do not have as strong opinion on this one and bug (links) was otherwise fixed

**Pull request closed without merging**
