### PR TITLE
ENH: refresh the copy of the player, provide previews (+commit reverted changes the # of cols)

### PR DESCRIPTION
**Pull request by yarikoptic**
Issue with passing the cols was recently fixed in https://github.com/asciinema/asciinema-player/commit/430b7f8c292d7e42173ee96d7f0fd86a19ed79c8

With 120 we would match the width of the text, and provide sufficient width for possibly long paths and outputs from datalad... problem was detected: http://github.com/asciinema/asciinema-player/issues/69 so I reverted the sizes  changes for now and thus changed the title ;)

Also done:
- [x] avoid boring black boxes -- specify time location for a preview

TODOs (not by me, dunno how)
- [ ] make width either configurable or depending on the rendering (mobile vs desktop)

### CODE REVIEW

**Comment by aqw** [comment]
@yarikoptic I thought you agreed before with my statement that this wasn't worth the effort. And you still havn't stated clearly what problem you are solving by doing this. I just see effort and the creation of problems.

---Alex

**Comment by yarikoptic** [comment]
on for the subject:  I agreed only that generating multiple asciinemas for multiple resolutions is too tedious.  I never agreed that we don't need sizes appropriate for the medium.
The problem is that too much output/comments are wrapping up ruining visual presentation in those screencasts, while there is a huge real estate of white space to the sides.   Making them wider, to at least match the width of the text, where possible, improves presentation for any desktop user, and for us giving presentations (not on the phones)

**Comment by aqw** [comment]
@yarikoptic Ahh, I missed that distinction. Understood now.

I'm cool with trying to make this wider; I'm concerned about the progress bars and other non-textual info and how that will distort across variable terminal widths.

asciinema-player is basically a replay-only, dumb TTY, and I've lurked on enough dev-lists for terminals to understand that re-flowing is really, really hard, and the bane of everything they hold dear.

---Alex

**Comment by yarikoptic** [comment]
yeah, progressbars etc would be at old length, but should be ok as long as we make it wider not narrower... unfortunately not entirely working atm (https://github.com/asciinema/asciinema-player/issues/69) that is why i reverted that change and ATM this PR is just an upgrade + providing the banner tuned for every screencast.  We could get back to this whenever they fix it up I guess.  I might need though to pre-record some custom ones for presentations meanwhile

**Comment by aqw** [comment]
@yarikoptic Ok, so they handle progress bars "correctly enough" in that they don't expand to width (which I wouldn't expect) but at least they don't cause reflow issues, yes? Then I am ok with having variable width as long as we always record 'casts at the smallest allowed width. We'll need to make darn sure all reflows happen correctly across all res changes -- especially mobile reorientation.

As for the preview image... I'm just still not sold. (Caveat, I have not run it locally yet; so havn't /actually/ seen it). It'll add visual busy-ness (meaning: taking eyes away from other things that are important), and I don't see what meaningful info it provides to the user. If the user reads it, sees info they're interested in, they click to play and the info disappears, and they have to wait until the info they're interested plays through. It just seems a bit counter-intuitive to me. I /do/ get the argument we have an opportunity to provide something more useful/interesting than a black box with a big-ass "play" symbol on it. I just don't have a good idea yet.

I will take a look at the previews, perhaps tomorrow, so I can comment on it more practically.

---Alex

**Comment by aqw** [comment]
@yarikoptic I liked your suggestion. Love all around. :-)

---Alex

**Comment by yarikoptic** [comment]
love -- awesome!
previews -- few more points:
- those are somewhat standard to have (youtube videos, asciinema.org hosted screencasts) etc -- everything has previews
- I specifically chosen the points in the screencasts with a state of demo exactly on a command which has direct relationship with the paragraphs.  Currently paragraphs are phrased for a new visitor, without noting datalad commands etc.  Having a brief screenshot with a good "representation" might prime the visitor to not get scared by the command line when he clicks "Play"

Here is an example:
demo

Note:  I took timings from when it was rendered wide and apparently for some of those now they are a bit off since some top lines now are gone (got wrapped), so for some would need to be adjusted.  but don't want to do it until we agree that it is the way to go

**Comment by yarikoptic** [comment]
another piece of history -- screencasts came as a compromise between just a static box with commands and narrated video scripts, whenever I was providing to Michael examples of other projects (dvc, etc) presenting their crucial features right on the single welcome page.  Seeing immediate that things are not that difficult and look neat (instead of lots of words + black box) is imho inviting to the users/visitors.

**Comment by yarikoptic** [comment]
@aqw do you mind if I add previews? wanted to get  your blessing before I spend time to adjust timing so it looks good

**Comment by aqw** [comment]
@yarikoptic So, looking at it, I don't think it visually distracts from the flow of the page (which was my only concern). And it does feel better than an empty black box. The text inside the 'cast is a bit noisy/effortful in that it's hard to discern between commands and comments, but that's unreleated to this PR and is certainly not a blocker. I havn't figured out yet how to send those color escape sequences using `xdotool`. :-/

Also, I made an "oops" in that I didn't realize you updated the asciinema-player in the PR. I just did that and updated the copyright page. I'll update this PR to fix the conflict and squash the commits. I hope to have time to poke at the CSS for variable widths as well.

---Alex

**Comment by aqw** [comment]
@yarikoptic Is it ok if I do a force push, squashing the commits and rebasing on master? Or is that poor form since it's your PR and it's erasing history?

Still learning the cultural norms of this collaborative PR thing.

---Alex

**Comment by aqw** [comment]
@yarikoptic So, I looked closer at the dynamic width thing, and while I do see the value is offering a >80 col view on wider viewports, this is starting to get ugly.

It looks like merely adjusting the CSS does not control the text flow (as I was hoping). Instead, the JS reads that col value, and the JS prints out the text in a way that forces a new line at the col-width. :-/

Meaning, this cannot be done easily using CSS. To do this, we would need a JS listener to fire on viewport size change, determine if it's at our "breakpoint", rewrite the cols attribute of all asciinema-player elements, and tell all of them to re-instantiate/reflow.

And IMO, that's not really a "good" or clean idea.

IMO, the preview posters are a nice win, we should get that in, and leave the variable terminal width thing as a good idea that just didn't land cleanly.

Thoughts?

---Alex

**Comment by yarikoptic** [comment]
IMHO better not to squash, so I could see what you did

**Comment by aqw** [comment]
@yarikoptic In the end, I didn't make any changes (since the CSS approach was unsuccessful). I just rebased on master (thus dropping the updated asciinema-player commit) and squashed. So I did nothing of real value.

As an aside, I am just finishing up edits to #24. Will push those to that PR soon.

---Alex

**Comment by yarikoptic** [comment]
Ok, whatever works. Thanks

**Comment by aqw** [comment]
@yarikoptic Sorry, I wasn't clear. I meant that I probably shouldn't push because I didn't create anything of value (other than simply the acts of squashing and rebasing). Unless you're saying otherwise now. Let me know what you'd prefer.

Also, any thoughts on my comment about the JS nature of the text-wrapping inside the asciinema-player?

---Alex

**Comment by yarikoptic** [comment]
My thoughts are that since their player doesn't work correctly ATM if we change cols, and if you don't see how to fix it - we should postpone the dynamic size feature for now. Re JS -- if that is the best way we could do it, then that would have been it.
Re previews, probably worth just redoing it in a clean (it squashed) branch with tiny adjustments to timing to make them look proper. I could do that later unless you beat me to it

As in current shape this PR is not to be merged, feel welcome to close it

**Comment by aqw** [comment]
@yarikoptic Sounds good on tabling the resize feature/discussion until it's supported properly by upstream.

I have a spare 20 min now. I'll do the previews real quick and save you the time.

---Alex

**Comment by aqw** [comment]
@yarikoptic Ugh, of course, I ran into a problem.

While testing this, I noticed that when I clicked "play" the page would hang and eventually, the 'cast would play, and skip ahead a bit.

My first thought was that this was due to the updated player, but apparently it's due to the previews.

When I load the page now, my CPU stays pegged for 9 seconds. Reverting the previews solves the problem.

My guess is that (since the previews are time based) every 'cast on the page starts playing itself at full speed in order to build the previews.

I'm going to start looking at the asciinema-player code, but I likely won't reach a resolution today before I have to switch to other tasks.

---Alex

**Comment by aqw** [comment]
@yarikoptic I took a quick glance at the code, and clojure is just too foreign to me to make quick sense of whether asciinema-player is playing the entire cast for every cast, or just playing up to what is needed (which would at least help to mitigate the problem).

I started playing with cheating and just using the "data:text/plain" method for the poster, but there's a bug where ASCII escape sequences aren't interpreted. So... there goes the brute-force method.

I filed a bug for the "data:text/plain" upstream and we'll see what comes of it.

---Alex

**Comment by yarikoptic** [comment]
yeah, doing the same as they do on their website and just provide base64 encoded (IIRC) preview would be the best to avoid that initial CPU load.  closure looked completely alien to me (even though I have tried to figure out what/how for us to do it easily)

re upstream bugs/issues -- thanks. Note: it often comes useful to have urls pointing to them so others (and ourselves later) could find those issues.

**Comment by aqw** [comment]
@yarikoptic Glad I'm not the only one who gets glassy-eyed reading Clojure. ;-)

Thanks for the pointer on the issue referencing: asciinema/asciinema-player#70

Worst case scenario we'll do the base64 method, but if I can use the plain-text method, I will; I want to avoid the base64 overhead if I can.

I'll wait and see what kind of resolution we get to the plaint text issue.

---Alex

**Comment by aqw** [comment]
@yarikoptic Ahh, I meant size overhead, not processing overhead. From what I understand, typical overhead for base64 is something like a 33% inflation of size. So I'd really rather use text than something like base64 encoded PNG.

**Comment by yarikoptic** [comment]
ah... I didn't know that it was the png encoded, thought it was just the text.  I guess with previews for all of them, even though screenshot should be quite well compressable, it would indeed result in quite a heavy html at the end.  I have no expertise/opinion to judge on either it would lead to impaired user experience, but I guess it might indeed especially when over mobile/slow connections.  
A somewhat obscure solution of cause could be to populate them on the fly by JS (may be just downloading the pngs and base64 encoding them?) at the end of the page processing ;)?  I am a bit surprised that we could not just point to png preview urls.

**Comment by yarikoptic** [comment]
BTW FWIW -- looked at one of the asciinemas (https://asciinema.org/a/134920) and its poster is actually a base64 encoded JSON, not a png. starts with `poster="data:application/json;base64,...`

**Comment by aqw** [comment]
@yarikoptic Nice find. I just assumed the primary use-case for base64 posters was PNGs. Great to hear it's JSON as well. I'll take a look at it.

---Alex

**Comment by aqw** [comment]
Fix upstream: https://github.com/asciinema/asciinema-player/commit/8d6fbbcfae8cea6764b2e47b15b3dc8e55803299

It should make this possible now, without PNGs nor the performance impact of specifying the time.

**Comment by yarikoptic** [comment]
Woohoo, cool!

**Comment by yarikoptic** [comment]
@aqw do you need help with the previews?  I guess this PR could be closed to be replaced with the new solution, right?

**Comment by aqw** [comment]
@yarikoptic I think asciinema can just be updated and it /should/ "just work".

**Comment by yarikoptic** [comment]
great, could you do it @aqw pretty please? ;-)  feel free and welcome to just close this PR since then it shouldn't be relevant or still might just serve aas the source of information for good time point to take as a representative state

**Comment by aqw** [comment]
Closing. Superseded by #42

**Pull request closed without merging**
