### PR TITLE
ENH(BK): Add youtube channel icon/link by the twitter

### LINKED ISSUE #37: Add reference to the youtube channel
https://www.youtube.com/channel/UCB8-Zf7D0DSzAsREoIt0Bvw

PS we need iirc 100 subscribers to reserve a name

### PR DESCRIPTION
**Pull request by yarikoptic**
Closes #37 

TODOs:
- [x] make that fontello icon to appear (I am not sure what needs to be done in addition)

@aqw please finish it up

### CODE REVIEW

**Comment by aqw** [comment]
@yarikoptic I have updated the fontello font, but I can't push to your branch. What is your preferred workflow? Do you want me to PR your PR? Do you want to grant me permissions? Push my own commit to master after merging yours?

Let me know. :-)

---Alex

Also, as FYI for updating fontello, I just simply do a manual process (though there are programmatic methods, I've just never bothered yet).
1) go to fontello.com
2) "import" the config.json file in theme/static/fonts/
3) search and add whatever glyph is needed
4) download and extract
5) overwrite fontello.woff, fontello.woff2, and config.json
6) port the added rule(s) from css/fontello.css to style.css

**Comment by yarikoptic** [comment]
> ontello font, but I can't push to your branch

Strange... You should be able to ... Sorry for seemingly silly question - did you try?

**Comment by aqw** [comment]
```
╭─aqw@brick ~/git/www.datalad.org on yarikoptic-enh-youtube
╰─➤ git push yarikoptic yarikoptic-enh-youtube
Enumerating objects: 19, done.
Counting objects: 100% (19/19), done.
Delta compression using up to 4 threads
Compressing objects: 100% (9/9), done.
Writing objects: 100% (10/10), 11.04 KiB | 5.52 MiB/s, done.
Total 10 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
To github.com:yarikoptic/datalad.org
 ! [remote rejected] yarikoptic-enh-youtube -> yarikoptic-enh-youtube (permission denied)
error: failed to push some refs to 'git@github.com:yarikoptic/datalad.org'
╭─aqw@brick ~/git/www.datalad.org on yarikoptic-enh-youtube
╰─➤ git remote show yarikoptic
* remote yarikoptic
  Fetch URL: git@github.com:yarikoptic/datalad.org
  Push  URL: git@github.com:yarikoptic/datalad.org
  HEAD branch: master
  Remote branches:
    enh-datasets tracked
    enh-heudi    tracked
    enh-index    tracked
    enh-search   tracked
    enh-widen    tracked
    enh-youtube  new (next fetch will store in remotes/yarikoptic)
    master       tracked
    nitpicking   tracked
  Local ref configured for 'git push':
    master pushes to master (fast-forwardable)

```

**Comment by aqw** [comment]
FML. And now I see it. Sigh....

I was trying to push to the 'yarikoptic-enh-youtube' branch, and in fact should have been pushing to 'enh-youtube'.

Sorry about the noise. it's pushed now.

**Comment by aqw** [comment]
Ok. Build passes. Merging.

**Comment by yarikoptic** [comment]
Thanks! sorry I've missed initial troubleshooting email, glad to see you figure it out.

**Pull request merged**
