### PR TITLE
WIP: Add github contributors to website footer

### PR DESCRIPTION
**Pull request by jsheunis**
See: https://github.com/datalad/datalad.org/issues/103

This PR adds github contributors to the website footer, as well as a github action to update these contributors once daily.

This is the process:

1. github action runs on a cron schedule
2. checkout master
3. run a shell script that:
   - loads existing contributors (each with login and avatar url) from json file
   - loads static list of repositories to check from txt file
   - makes a curl request for all contributors of a repository
   - prunes the response objects to only include login and avatar fields
   - merges the array of objects with the array of existing contributors
   - write merged list to existing json file
4. commit and push changes file to master
5. run the rest of deployment steps to push changes to gh-pages branch (same steps as the on:push action)

TODO:

- [x] add full list of repositories to txt file

### CODE REVIEW

**Comment by yarikoptic** [comment]
Following up on my comment during meetup: please  checkout https://github.com/con/tributors which we use in datalad "core": https://github.com/datalad/datalad/blob/master/.github/workflows/update-contributors.yml . Ideally such workflow/action should be provided just by a parametrized action to avoid duplication.  I think @vsoch started to work on one (in https://github.com/con/tributors/pull/2) at some point.

**Comment by vsoch** [comment]
We also have an example in https://github.com/USRSE/usrse.github.io/blob/main/.github/workflows/update-contributors.yaml !

**Comment by jsheunis** [comment]
@yarikoptic If I understand the tributors tool directly, it operates on a specific repository and collates all contributors from various sources (all-contributors, zenodo, etc) into the `.tributors` file for that repository. I think in the current use case of the website, this is not directly applicable since for the website I want to merge all contributors to the DataLad ecosystem from various repositories. What would make sense to me is to keep the current action, but to also inspect `.tributors` files in case they are available in repositories being inspected (since the .tributors files might contain more contributors than what is available via the GitHub API).

A second point is that I also want to fetch the respective GitHub avatars of contributors, which doesn't look like it's available via tributors in its current state.

**Comment by jsheunis** [comment]
Thanks, good to understand the delineation and overlap of these use cases.

**Pull request closed without merging**
