### PR TITLE
Put GIN on integrations page

### PR DESCRIPTION
**Pull request by mih**

### CODE REVIEW

**Comment by yarikoptic** [comment]
I would have placed gin into a dedicated section: "datalad compatible solutions" or alike to make it clear that gin is not using/relying on datalad, like the other items in the list. Iirc the original intention for this just was to list downstream projects.

And then added there GitHub, gitlab, and as a single entry probably a long list of supported special remotes (aws s3, ...)

**Comment by mih** [comment]
I am fine with whatever approach. Please edit as you see fit.

**Comment by yarikoptic** [comment]
Ok then might get to it later, can and let's merge meanwhile although IMHO it is a bit misleading

**Comment by mih** [comment]
Ok, will merge. But FTR: I think there is a lot of value in just documenting what works right now. A number of people will not care *why* things are working (drive-by usage, formal collaboration, etc.), but do care *what* things are working. I am fine to have a place that only lists technically correct downstream usage, as long as we also have that other list that can be pointed to. ATM this is the only page we have AFAIK.

**Pull request merged**
