### PR TITLE
Add Mastodon social link

### PR DESCRIPTION
**Pull request by adswa**
I lack foo for the [icon](https://fontawesome.com/v5/icons/mastodon?s=solid&f=brands): 
image
pls help...

### CODE REVIEW

**Comment by jsheunis** [comment]
Screenshot 2022-11-11 at 21 36 41
Screenshot 2022-11-11 at 21 36 32

**Comment by adswa** [comment]
This is awesome, thx much @jsheunis! I presume my computer has an encoding issue - for some reason this is what I see. But even that is better than no icon.  

image

**Comment by aqw** [comment]
The SVG font is not needed (and is not referenced in the CSS file anyway). Otherwise, this PR looks good.

**Comment by aqw** [comment]
I removed the SVG font and updated the hash to address Adina's problem.

**Pull request merged**
