### PR TITLE
Adds netlify badge to footer

### PR DESCRIPTION
**Pull request by jsheunis**
I'd like to apply for [Netlify's open source plan](https://www.netlify.com/legal/open-source-policy), which gives Pro accounts for free for open source projects. One requirement, apart from a few standard stuff that we already have (open source license, code of conduct), is that we have to refer to Netlify on our "main site" by using a badge or a phrase like "Deploys by Netlify".  This PR adds such a badge and link to the website footer.

Benefits of deploying with netlify:

- it integrates easily with github repos
- it supports deploy previews (e.g. alternative branches, or pull request deploys) which we can use for this website as well as datalad-catalog, perhaps other projects as well?
- it supports server configuration such as specifying redirects (which github pages doesn't support, and which is needed for a soon to be deployed version of datalad-catalog, see https://github.com/psychoinformatics-de/sfb1451-projects-catalog/pull/83)

### CODE REVIEW

**Comment by jsheunis** [comment]
Screenshots of local tests:

Screenshot 2024-02-05 at 14 37 02

Screenshot 2024-02-05 at 14 37 10

**Comment by yarikoptic** [comment]
I don't mind.  How strict they are on the phrase etc -- I wonder if it could be more harmoneously integrated by simply having netlify logo in line up of logos there in the same coloring etc?

**Comment by jsheunis** [comment]
> I don't mind. How strict they are on the phrase etc -- I wonder if it could be more harmoneously integrated by simply having netlify logo in line up of logos there in the same coloring etc?

Good idea, I will see how strict they are.

**Comment by mih** [comment]
Given there was no activity in the past months, I am merging this for sanity reasons.

**Comment by mih** [comment]
image

Alignment is not looking optimal.

**Pull request merged**
