### PR TITLE
ENH: added basic search cast

### PR DESCRIPTION
**Pull request by yarikoptic**
BTW, it seems that some links in top list of content do not work, e.g. "Reproducible Science". Also some titles do not correspond exactly.

Both resolutions (Small and Big) of screencast also posted at https://asciinema.org/~DataLad

### CODE REVIEW

**Comment by mih** [comment]
Great, thanks. Few issues though:

We have to further limit the width of the formatted description parts. Directory here is 'datalad' not 'demo', which is slightly longer, hence led to wrapping in one instance (single char).

There is no demo dataset in this case, hence the casts ends with

`[ERROR] path not associated with any dataset [remove(/demo/demo)] `

we should protect that.

At one point you do `cat openfmri/ds000105/dataset_description.json` -- maybe switch to `cat openfmri/ds000105/dataset_description.json | json_pp`. Not sure how it would look in the small terminal, but it would be less of a text "blob".

**Comment by aqw** [comment]
@yarikoptic Hmm, those broken headers seem due to using the `headerid` plugin. I'll taker a look at it to see why/how it's changing those header IDs.

---Alex

**Comment by mih** [comment]
I created a mess, will take care of the conflicts. Would be good to update the rendered cast anyways in the future...

ALSO: I think the idea to associate DataLad's functionality with the FAIR principles is great. It might actually be worth its own page, or a box on the frontpage. I would, however, not hide it in a feature demo section. We should cover (some aspect of) the entire F A I R, but that point is easily lost when scattered across the demos.

**Comment by yarikoptic** [comment]
Features page sounds appropriate, we could have a preface and then FAIR aspects through it all items as a white thread. 
We are the FAIRest of all IMHO

**Comment by mih** [comment]
I fear that a need to categorize feature in terms of the FAIR principles is more constraining than helpful. I agree with being "FAIR" is a feature, and as such it could be on the feature page, but it should not "contaminate" any demo that might be focusing on something entirely different.

**Comment by yarikoptic** [comment]
yeah, agree

**Pull request merged**
