### PR TITLE
Feature demo: minimal operation for novices

### PR DESCRIPTION
**Pull request by mih**
@aqw Can you please have a look re language and clarity? Thx!

### CODE REVIEW

**Comment by aqw** [comment]
@mih Made some tweaks. Pushed to branch.

**Comment by mih** [comment]
@aqw Gracie!

**Comment by mih** [comment]
I would appreciate to get this merged now and edit it again once the revolution merge procedure is done. What is described here comes up in every meeting on datalad use I have, and it is very suboptimal to not be able to point to the main page to communicate that datalad can do this.

**Comment by mih** [comment]
Oh, it seems that this discussion is pointless, as the changes are already published on the main website. I suspect that the deployment setup is wrong in some way. The content of a proposed PR should not automatically replace the main website. Can you have a look at this please @aqw ?

**Comment by aqw** [comment]
@mih Looking. Not entirely clear why it behaved this way. The logs sure imply that the deployment script was never run. But obviously it was. Poking at this.

**Comment by yarikoptic** [comment]
Yeap
https://travis-ci.org/datalad/datalad.org/builds/461784941

**Comment by aqw** [comment]
@yarikoptic Yep; you're right. I was so focused on it checking for whether it was a PR or not, I forgot that this'll run on all branches, and the PR comes from a branch in this repo.

**Comment by mih** [comment]
@aqw You force pushed the master branch and this PR branch. Now they are in conflict with each other. Please let me know how this should be resolved. Thx.

**Comment by aqw** [comment]
@mih Sorry about that. I was doing force pushes because I wanted to avoid a pile of "testing" commits as I was trying to figure out why the deploy script doesn't run.

Working to resolve it, but the latency until Travis jobs actually run is slowing this down.

**Comment by aqw** [comment]
@mih @yarikoptic Branch/PR building is resolved in 9b2cb6160cebf89ccf531b3f592f093c4f6ab787

Everything seems to be working now. Will merge, as per mih's request.

**Comment by aqw** [comment]
@yarikoptic As FYI, there are no checks for a 'gh-pages' branch because apparently that's a magic branch name, and Travis, by default, will not execute jobs for that branch.

**Pull request merged**
